### ISSUE TITLE
Brand QR code with Block M

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/z#146]
Feature request: https://tdx.umn.edu/TDNext/Apps/29/Tickets/TicketDet.aspx?TicketID=1196246

**Comment by cmcfadden** [comment]
I vote we use Goldy's face. I can't see anyone objecting.

**Comment by cmcfadden** [comment]
"All marks are reserved for official University business and may not be used to promote non-University activities or imply endorsement."
