### ISSUE TITLE
Transparent background on png?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/z#152]
Amanda (https://tdx.umn.edu/TDNext/Apps/29/Tickets/TicketDet.aspx?TicketID=1387722) requested that we make the background for the PNGs transparent. 

We'd need to think about the downsides - IE, if someone drops one into a powerpoint with a darker background, would it prevent scanning? How hard would it be for them to fix that themselves?

**Comment by jxjj** [comment]
This makes sense to me. 

Yeah, clients in dark mode will probably be an issue. For example, if a user has Canvas, Google Docs, their email client in dark mode – will the qr code be visible? Probably depends on client.

Thoughts:
- Maybe make the color scheme user selectable? B/W, B/transparent, Maroon/Gold?
- Maybe changing to svg would be make customization easier? Scaling and changing fill should be cake. And maybe svg support for media queries like `@media (prefers-color-scheme: dark)` is possible? But, this could have it's own set of tradeoffs.

What are your thoughts?

**Comment by cmcfadden** [comment]
My guess is that folks sophisticated enough to use an SVG would also be sophisticated enough to make their own QR code if need be. Giving folks multiple options makes sense - maybe take the QR code button and make it a multifunction thing - just clicking it gets you the current black on white, but with a pulldown arrow on the right side that lets you grab others? We can chat.

**Comment by cmcfadden** [comment]
Updating this to note that Josie (https://tdx.umn.edu/TDNext/Apps/29/Tickets/TicketDet.aspx?TicketID=1415747) requested this too
